# version: "3.9"
services:
  manager_api:
    container_name: manager_api
    build:
      context: .
      dockerfile: containers/api/Dockerfile
    env_file:
      - containers/api/api.env
    networks:
      - my_network
    ports:
      - 5000:5000
    # depends_on:
    #   manager_db:
    #     condition: service_healthy
  
  manager_reporting_api:
    container_name: manager_reporting_api
    build:
      context: . # 👈 raíz del proyecto
      dockerfile: containers/reporting_api/Dockerfile
    env_file:
      - containers/reporting_api/reporting_api.env
    networks:
      - my_network
    ports:
      - 5001:5000  # 👈 expone en tu host (5001) la API de Reporting (puerto interno 5000)
    depends_on:
      - manager_api   # 👈 si depende de la API principal

  # manager_db:
  #   image: mcr.microsoft.com/mssql/server:2019-latest
  #   container_name: manager_db
  #   env_file:
  #     - containers/db/db.env
  #   networks:
  #     - my_network
  #   healthcheck:
  #     test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P $${SA_PASSWORD} -Q 'SELECT 1' || exit 1"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 10
  
  # manager_esb:
  #   container_name: manager_esb
  #   image: rabbitmq:3-management
  #   ports:
  #     - 5672:5672
  #     - 15672:15672
  #   networks:
  #     - my_network

  manager_ui:
    container_name: manager_ui
    build:
      context: ../../Frontend/packages/main # 👈 aquí va la carpeta raíz de tu Angular (donde está package.json)
      dockerfile: Dockerfile
    ports:
      - "4200:80" # Angular disponible en http://localhost:4200
    networks:
      - my_network
    depends_on:
      - manager_api
  
networks:
  my_network:
    driver: bridge

volumes:
  manager_db_data:   # 👈 aquí declaras el volumen persistente